In [10]:
import yaml
import numpy as np
from sklearn import tree

with open("invariants.yml", 'r') as stream:
    invariants = yaml.load(stream)

print(invariants)

{'A': {1: 0.23474448546927168, 2: 0.014131899712309343, 3: 0.0022068639536710196, 4: 4.005609203212841e-05, 5: 4.523939410069149e-09, 6: -3.0175208987616873e-06, 7: -1.101672722634215e-08}, 'B': {1: 0.21676249774658607, 2: 0.009647234224541718, 3: 0.00019284632874368583, 4: 4.511503382685754e-08, 5: -1.281049124748357e-13, 6: 2.007505561995701e-09, 7: -3.6018950591548056e-14}, 'S': {1: 0.30294848571943284, 2: 0.03528541922067088, 3: 0.0038641394930697204, 4: 0.00026573039351812135, 5: 7.808369610746823e-08, 6: 7.922112462596876e-06, 7: 2.577001370668313e-07}, 'U': {1: 0.24387254775432934, 2: 0.012759721924066072, 3: 0.0002822703318846717, 4: 6.409213044540052e-05, 5: 8.349616511641995e-09, 6: 3.64825210317783e-06, 7: 2.1446202840149167e-09}, 'W': {1: 0.22595113772437472, 2: 0.004719834054789419, 3: 0.0010793208686020557, 4: 0.00013370592405118078, 5: 4.961290078948066e-08, 6: 8.678362672287337e-06, 7: 1.0883841339829872e-08}, 'Y': {1: 0.346964473516744, 2: 0.04169580673971174, 3: 0.026

In [7]:
import pydotplus

X = list([list(invs.values()) for invs in list(invariants.values())])
Y = list(invariants.keys())
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X, Y)

dot_data = tree.export_graphviz(clf, out_file=None)
graph = pydotplus.graph_from_dot_data(dot_data)
graph.write_pdf("iris.pdf")

True

In [13]:
arr = np.array([[0, 0, 255, 255],[255, 0, 0, 0]])


In [15]:
arr.size

8

In [26]:
arr.flatten()

array([  0,   0, 255, 255, 255,   0,   0,   0])

In [34]:
np.bincount(arr.flatten())[255]

3

array([  0,   0, 255, 255, 255,   0,   0,   0])

In [38]:
from collections import defaultdict
d = defaultdict(list)
d[1].append("jeden")
d

defaultdict(list, {1: ['jeden']})

In [57]:
def cartesian(arrays, out=None):
    """
    Generate a cartesian product of input arrays.

    Parameters
    ----------
    arrays : list of array-like
        1-D arrays to form the cartesian product of.
    out : ndarray
        Array to place the cartesian product in.

    Returns
    -------
    out : ndarray
        2-D array of shape (M, len(arrays)) containing cartesian products
        formed of input arrays.

    Examples
    --------
    >>> cartesian(([1, 2, 3], [4, 5], [6, 7]))
    array([[1, 4, 6],
           [1, 4, 7],
           [1, 5, 6],
           [1, 5, 7],
           [2, 4, 6],
           [2, 4, 7],
           [2, 5, 6],
           [2, 5, 7],
           [3, 4, 6],
           [3, 4, 7],
           [3, 5, 6],
           [3, 5, 7]])

    """

    dtype = arrays[0].dtype

    n = np.prod([x.size for x in arrays])
    if out is None:
        out = np.zeros([n, len(arrays)], dtype=dtype)

    m = int(n / arrays[0].size)
    out[:,0] = np.repeat(arrays[0], m)
    if arrays[1:]:
        cartesian(arrays[1:], out=out[0:m,1:])
        for j in range(1, arrays[0].size):
            out[j*m:(j+1)*m,1:] = out[0:m,1:]
    return out

In [59]:
cartesian(([np.array([1, 2]), np.array([3,4])], [10], [100, 200]))

AttributeError: 'list' object has no attribute 'dtype'