In [48]:
import numpy as np
X = np.array([1, 2, 3])
X.reshape(-1, 1)
X[1:2]

array([2])

In [59]:
image = np.resize(np.arange(1,100), (10,10))
print(image)
x = [2,3,4]
y = [3,8]
marker = 0
image[min(y):max(y) , min(x)] = marker
image[max(y) , min(x):max(x) + 1] = marker
image[min(y), min(x):max(x)] = marker
image[min(y):max(y) , max(x)] = marker

print(image)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]
 [51 52 53 54 55 56 57 58 59 60]
 [61 62 63 64 65 66 67 68 69 70]
 [71 72 73 74 75 76 77 78 79 80]
 [81 82 83 84 85 86 87 88 89 90]
 [91 92 93 94 95 96 97 98 99  1]]
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32  0  0  0 36 37 38 39 40]
 [41 42  0 44  0 46 47 48 49 50]
 [51 52  0 54  0 56 57 58 59 60]
 [61 62  0 64  0 66 67 68 69 70]
 [71 72  0 74  0 76 77 78 79 80]
 [81 82  0  0  0 86 87 88 89 90]
 [91 92 93 94 95 96 97 98 99  1]]


In [69]:
arr = [(1, 2),(1, 4), (5, 1)]
arr.sort(key=lambda comb, val: comb[1])
print(arr)

TypeError: <lambda>() missing 1 required positional argument: 'val'

In [76]:
foo = {"foo": 12, "bar" : 12}

all([k in foo for k in ["foo","bar"]])

True

In [79]:
import datetime

now = datetime.datetime.now()

In [80]:
then = datetime.datetime.now()

In [85]:
(then - now).total_seconds()

8.947199